version: '3.9'

# Quando utilizar redes específicas
networks:
  network_private:
    driver: bridge
  network_public:
    driver: bridge
    #external: true

services:
  site_system:
    build:
      context: .docker/
      dockerfile: Dockerfile
    container_name: conteiner_site_system
    # command: [".docker/wait-for-it.sh", "db_paulistense:3306", "-t", "30"]
    # ports: 
      # - '80:80'
      #- '443:443' #quando utilizar um certificado especificar essa porta
    networks:
      - network_private
      - network_public
    volumes:
      - .:/var/www/html
    environment:
      - BANCO_HOST_IP=$BANCO_HOST_IP
      - BANCO_PORTA=$BANCO_PORTA
      - BANCO_USUARIO=$BANCO_USUARIO
      - BANCO_SENHA=$BANCO_SENHA
      - BANCO_NOME=$BANCO_NOME
    links:
      - db_paulistense
        
  db_paulistense:
    image: mysql:latest
    container_name: container_db_paulistense
    ports: #para teste
      - '3306:3306' #para teste
    networks:
      - network_private
      - network_public #para teste
    volumes:
      - '.docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    environment:
      - MYSQL_ROOT_PASSWORD=$BANCO_SENHA
      - MYSQL_USER=$BANCO_USUARIO
      - MYSQL_PASS=$BANCO_SENHA
  
  site_proxy:
    build: ./nginx
    container_name: container_site_proxy
    ports:
      - "80:80"
    networks:
      - network_public
    links:
      - site_system